In [38]:
## 使用 Python 进行 k-最近邻分类。地址：http://suo.im/2zqW0t
import numpy as np
from sklearn import neighbors, datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target

In [39]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X, y)
z = clf.predict(X)
accuracy = clf.score(X, y)
print("Predicted model accuracy:" + str(accuracy))
A = np.vstack([y, z])
print(A)

Predicted model accuracy:0.966666666667
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
  2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  2 2]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
  1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
  2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
  2 2]]


In [40]:
import numpy as np
from sklearn import neighbors
import pandas as pd

df = pd.read_table("/Users/liuchang/Desktop/iris.data.txt", sep=",")

X = df.iloc[:, 0:4] ## X includes columns 0,1,2,3
print(X)

     5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
5    4.6  3.4  1.4  0.3
6    5.0  3.4  1.5  0.2
7    4.4  2.9  1.4  0.2
8    4.9  3.1  1.5  0.1
9    5.4  3.7  1.5  0.2
10   4.8  3.4  1.6  0.2
11   4.8  3.0  1.4  0.1
12   4.3  3.0  1.1  0.1
13   5.8  4.0  1.2  0.2
14   5.7  4.4  1.5  0.4
15   5.4  3.9  1.3  0.4
16   5.1  3.5  1.4  0.3
17   5.7  3.8  1.7  0.3
18   5.1  3.8  1.5  0.3
19   5.4  3.4  1.7  0.2
20   5.1  3.7  1.5  0.4
21   4.6  3.6  1.0  0.2
22   5.1  3.3  1.7  0.5
23   4.8  3.4  1.9  0.2
24   5.0  3.0  1.6  0.2
25   5.0  3.4  1.6  0.4
26   5.2  3.5  1.5  0.2
27   5.2  3.4  1.4  0.2
28   4.7  3.2  1.6  0.2
29   4.8  3.1  1.6  0.2
..   ...  ...  ...  ...
119  6.9  3.2  5.7  2.3
120  5.6  2.8  4.9  2.0
121  7.7  2.8  6.7  2.0
122  6.3  2.7  4.9  1.8
123  6.7  3.3  5.7  2.1
124  7.2  3.2  6.0  1.8
125  6.2  2.8  4.8  1.8
126  6.1  3.0  4.9  1.8
127  6.4  2.8  5.6  2.1
128  7.2  3.0  5

In [41]:
y = df.iloc[:, 4:5]
print(y)

        Iris-setosa
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
5       Iris-setosa
6       Iris-setosa
7       Iris-setosa
8       Iris-setosa
9       Iris-setosa
10      Iris-setosa
11      Iris-setosa
12      Iris-setosa
13      Iris-setosa
14      Iris-setosa
15      Iris-setosa
16      Iris-setosa
17      Iris-setosa
18      Iris-setosa
19      Iris-setosa
20      Iris-setosa
21      Iris-setosa
22      Iris-setosa
23      Iris-setosa
24      Iris-setosa
25      Iris-setosa
26      Iris-setosa
27      Iris-setosa
28      Iris-setosa
29      Iris-setosa
..              ...
119  Iris-virginica
120  Iris-virginica
121  Iris-virginica
122  Iris-virginica
123  Iris-virginica
124  Iris-virginica
125  Iris-virginica
126  Iris-virginica
127  Iris-virginica
128  Iris-virginica
129  Iris-virginica
130  Iris-virginica
131  Iris-virginica
132  Iris-virginica
133  Iris-virginica
134  Iris-virginica
135  Iris-virginica
136  Iris-virginica


In [42]:
clf = neighbors.KNeighborsClassifier()
clf.fit(X, y)
z = clf.predict(X)
accuracy = clf.score(X, y)
print("Predicted model accuracy:" + str(accuracy))

Predicted model accuracy:0.96644295302


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [46]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, y)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [48]:
clf.predict([[2., 2.], [-1., -2.]])

array([1, 0])

In [50]:
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 2), (2, 1)]

In [51]:
clf.predict_proba([[2., 2.], [1., 2.]])

array([[  1.96718015e-04,   9.99803282e-01],
       [  1.96718015e-04,   9.99803282e-01]])

In [52]:
X = [[0., 0.], [1., 1.]]
y = [[0,1],[1,1]]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                   hidden_layer_sizes=(15,),random_state=1)
clf.fit(X, y)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [53]:
clf.predict([[1., 2.]])

array([[1, 1]])

In [54]:
clf.predict([[0., 0.]])

array([[0, 1]])