In [1]:
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
print(a.shape)

(3,)


In [3]:
print(a[0], a[1])

1 2


In [4]:
a[0] = 5
print(a[0])

5


In [5]:
#快速创建几种内置的数组样式
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))

In [7]:
print(b)

[[1. 1.]]


In [8]:
c = np.full((2,2), 7)

In [9]:
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(2)

In [11]:
print(d)

[[1. 0.]
 [0. 1.]]


In [12]:
e = np.random.random((2,2))
print(e)

[[0.57588254 0.08820089]
 [0.49988576 0.38120435]]


In [13]:
## 多维数组的切片
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [15]:
b[0,0] = 77
print(a[0,1])

77


In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [18]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,1]]))
print(a[[0,0], [1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 6]
[2 2]
[2 2]


In [19]:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [20]:
## 数组计算
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [21]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [22]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [23]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [24]:
print(x*y)

[[ 5. 12.]
 [21. 32.]]


In [25]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [26]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x.dot(v))
print(np.dot(x,v))

[29 67]
[29 67]


In [30]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x, axis=0)) ## 计算所有列之和
print(np.sum(x, axis=1)) ## 计算所有行之和

10
[4 6]
[3 7]


In [31]:
## 矩阵转置
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [32]:
## Numpy的广播机制 
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)  ## Create an empty matrix with the same

for i in range(4):
    y[i,:] = x[i,:] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [33]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [34]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [35]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
## 广播机制例子
## Compute outer product of vectors
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v, (3,1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [37]:
x = np.array([[1,2,3], [4,5,6]])
print(x+v)

[[2 4 6]
 [5 7 9]]


In [38]:
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]
