In [2]:
from numpy.random import randn #导入numpy.random.randn
import numpy as np # 导入numpy
data = randn(2,3) # 随机生成2*3的数组
print(data)

[[-0.22756175  0.17232018 -1.9794246 ]
 [ 0.87822328  0.50534213  0.75368641]]


In [3]:
print(data*10)

[[ -2.27561746   1.72320184 -19.79424602]
 [  8.78223279   5.05342134   7.53686411]]


In [4]:
print(data+data)
print(data.shape)
print(data.dtype)

[[-0.45512349  0.34464037 -3.9588492 ]
 [ 1.75644656  1.01068427  1.50737282]]
(2, 3)
float64


In [5]:
# 创建多维数组 最简单的方法是使用array函数 它接受一切序列型的对象
data2 = [[1,2,3],[4,5,6]]
arr2 = np.array(data2) # 得到一个二维数组
print(arr2)
a = np.zeros((2,2))
print(a)


[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]]


In [6]:
b = np.zeros((2,2)) #创建指定形状的全0数组
print(b)
c = np.ones((2,3)) #创建指定形状的全1数组
print(c)
d = np.empty((2,3,2)) #创建指定形状的随机数组
print(d)


[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[-2.00000000e+000  2.00389835e+000]
  [ 2.96439388e-323  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]]

 [[ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  0.00000000e+000]
  [ 0.00000000e+000  8.34402697e-309]]]


In [7]:
e = np.arange(5) # arange是Python内置函数range的数组版
print(e)

[0 1 2 3 4]


In [8]:
# 多维数组的dtype
typearr = np.array([1,2,3], dtype=np.float64)
print(typearr)

[1. 2. 3.]


In [9]:
typearr2 = typearr.astype(np.int64)
print(typearr2)

[1 2 3]


In [10]:
# 数组很重要 因为它使我们不用编写循环即可对数据执行批量运算
data = randn(2,3) # 随机生成2*3的数组
print(data)
print(data*10)
print(data + data)

[[-1.00158314  0.17092243  0.00517985]
 [ 0.79269954  1.14046019 -1.67139684]]
[[-10.01583145   1.70922434   0.05179852]
 [  7.92699543  11.40460187 -16.71396841]]
[[-2.00316629  0.34184487  0.0103597 ]
 [ 1.58539909  2.28092037 -3.34279368]]


In [14]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[5:8])


[5 6 7]


In [15]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [16]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [17]:
arr_slice[:] = 100
print(arr)


[  0   1   2   3   4 100 100 100   8   9]


In [18]:
arr_copy = arr[5:8]
print(arr_copy)
arr_copy = arr[5:8].copy()
arr_copy[:] = 0
print(arr)

[100 100 100]
[  0   1   2   3   4 100 100 100   8   9]


In [19]:
# Numpy数组和Python列表最重要的一点在于，数组切片是原始数组的试图，
# 数据不会被复制，在试图的基础上进行的任何修改都会直接反映到源数组上。
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2])
print(arr2d[0:1][0:1])


[7 8 9]
[[1 2 3]]


In [20]:
print(arr2d[0:1])

[[1 2 3]]


In [21]:
# 多维数组可以用[][]的方式或者[,]方式索引，但不能用(,)方式索引
print(arr2d[0,0])

1


In [22]:
# 布尔型索引
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [23]:
data = randn(7,4)
print(data)

[[ 0.27846996  0.46315577  0.06565614 -0.12558744]
 [-0.95646438  0.5185384  -0.40036805 -0.3461322 ]
 [ 0.59765413 -0.05855634  0.33043843  0.55108733]
 [-2.25696431  1.77714533 -1.02662503  1.71479533]
 [-0.14303621 -0.27038266  0.3842841  -1.47045123]
 [-0.15849181 -0.7564386   0.75888712  0.95072526]
 [ 0.66763971 -2.09297349 -0.37140192 -1.71455978]]


In [24]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [25]:
data[names == 'Bob']

array([[ 0.27846996,  0.46315577,  0.06565614, -0.12558744],
       [-2.25696431,  1.77714533, -1.02662503,  1.71479533]])

In [42]:
data[data<0] = 0
print(data)

[[0.27846996 0.46315577 0.06565614 0.        ]
 [0.         0.5185384  0.         0.        ]
 [0.59765413 0.         0.33043843 0.55108733]
 [0.         1.77714533 0.         1.71479533]
 [0.         0.         0.3842841  0.        ]
 [0.         0.         0.75888712 0.95072526]
 [0.66763971 0.         0.         0.        ]]


In [36]:
#数学统计方法 可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算
arr = np.random.randn(5,4) # 正态分布的数据
print(arr)

[[-0.32398779  0.336456   -1.55965147 -0.82240335]
 [-2.87940885 -2.6031584   0.79509981  2.07667413]
 [-1.79486008  0.58973396  0.20727667  0.20697509]
 [ 1.6140764  -0.10737957 -0.5449914   0.83140089]
 [-0.42993874  1.539873    1.92774623 -1.84909004]]


In [27]:
# 数组转置和轴对称
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [28]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [29]:
# 对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [32]:
print(arr.mean())

-0.14917231163871875


In [33]:
print(arr.sum())

-2.9834462327743747


In [34]:
print(arr.sum(axis=0)) # 对每一列进行求和
print(arr.sum(axis=1)) # 对每一行进行求和

[-1.62211951  2.6382684  -0.61133539 -3.38825973]
[-2.438866    0.97966016 -2.56518917  0.42243137  0.61851741]


In [38]:
from numpy.linalg import inv, qr
X = randn(5,5)
print(X)

[[ 0.8072352   0.48968784  1.07810478 -0.42918348 -0.73746939]
 [-0.2314971  -2.17091688  0.66569674  0.31671043 -0.64419123]
 [-0.05977592  0.16225607 -0.89877431 -0.26892486  1.36006507]
 [-1.44899125 -0.253148   -0.26936334 -1.12534885  0.15312413]
 [-1.21627265 -0.1034773  -0.28053202  1.91770212  1.20264655]]


In [39]:
mat = X.T.dot(X)
print(mat)

[[ 4.28768752  1.38082106  1.50141087 -1.10552233 -2.21210362]
 [ 1.38082106  5.05379278 -0.9658516  -0.85491148  1.09482495]
 [ 1.50141087 -0.9658516   2.56451215 -0.24501804 -2.82492372]
 [-1.10552233 -0.85491148 -0.24501804  5.30081597  1.88073207]
 [-2.21210362  1.09482495 -2.82492372  1.88073207  4.27842617]]
